name: master
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches: [master, main]
    tags: ["*"]

jobs:
  build-querydb:
    concurrency: master
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache SBT and Coursier dependencies
      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}

      # Build querydb.zip using the querydb project
      - run: sbt "project querydb" createDistribution

      # Upload querydb.zip to a hardcoded release URL
      - name: Upload querydb.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: querydb/target/querydb.zip
          asset_name: querydb.zip
          asset_content_type: application/zip
