name: release
on:
  schedule:
    - cron: "0 7 * * *" # run once daily
  workflow_dispatch:    # allow to manually trigger this workflow
jobs:
  release:
    if: github.repository_owner != 'joernio'
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: sbt "project querydb" createDistribution
      - name: Upload querydb.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: querydb/target/querydb.zip
          asset_name: querydb.zip
          asset_content_type: application/zip
